### ISSUE TITLE
Buttons not working in Electron 1.0?

### ISSUE THREAD

**Issue by janis-me** [srakowski/ElectronLikeVS#1]
Hey!

I am using Electron 1.0 and all the code you provided, but my buttons don't work. I get an error that electron couldn't find the "remote" method. Trying to switch to " ('electron').remote " puts out other errors. Do you may have a solution for me?

**Comment by janis-me** [comment]
Ah, got it. Only had to use `const {BrowserWindow} = require('electron').remote;`.

**Comment by srakowski** [comment]
I'll have to update the example for Electron 1.0. Thank you for bringing this to my attention.
